In [1]:
import numpy as np

In [2]:
a = np.array([
    [1,6],
    [2,8],
    [3,11],
    [3,10],
    [1,7]
])

#### Среднее значение признака

In [7]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

#### Вычитание среднего

In [10]:
a_centered = a-mean_a

In [11]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### Скалярное произведение столбцов

In [18]:
b = a_centered.transpose()
b

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

In [23]:
c_vec = np.array([-1. ,  0. ,  1. ,  1. , -1. ])

In [25]:
d_vec = np.array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [31]:
a_centered_sp = np.dot(c_vec,d_vec)

In [32]:
a_centered_sp

8.0

In [47]:
ttl = a_centered_sp/(5-1)
ttl

2.0

In [36]:
A = a.T
A

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [40]:
cov = np.cov(A)
cov

array([[1. , 2. ],
       [2. , 4.3]])