In [38]:
import numpy as np

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [39]:
a = np.arange(12,24)
a
    

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [40]:
a1 = a.reshape(2,6)
a2 = a.reshape(6,2)
a3 = a.reshape(4,3)
a4 = a.reshape(3,4)
a5 = a.reshape(12,1)
a1,a2,a3,a4,a5


(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 
(в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [41]:
a6 = a.reshape(2,-1)
a7 = a.reshape(6,-1)
a8 = a.reshape(4,-1)
a9 = a.reshape(-1,4)
a10 = a.reshape(-1,1)
a6,a7,a8,a9,a10

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

4.Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Нет. Он двумерный.

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со 
средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же 
атрибутом size, как и исходный массив.

In [42]:
b = np.random.randn(3,4)
b

array([[-2.36763269,  0.48131949,  1.34270123,  0.93335157],
       [ 0.02765636, -0.60527507, -1.72151084, -0.72176113],
       [-1.66301896, -0.10216536, -1.55379112, -1.57972735]])

In [43]:
b.size

12

In [44]:
c =b.flatten()
c

array([-2.36763269,  0.48131949,  1.34270123,  0.93335157,  0.02765636,
       -0.60527507, -1.72151084, -0.72176113, -1.66301896, -0.10216536,
       -1.55379112, -1.57972735])

In [45]:
c.size

12

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [46]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 
    В чем разница между массивами a и b?

In [47]:
b = np.arange(20,1,-2).reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [48]:
a.shape

(10,)

In [49]:
b.shape

(1, 10)

Разница в том, что массив b-двумерный.

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [63]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [64]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [65]:
v = np.vstack((a,b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [66]:
v.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. 
Получить матрицу At путем транспонирования матрицы A. 
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 
Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [71]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [74]:
A = a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [75]:
At= A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [76]:
B = np.dot(A,At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [77]:
B.size

16

#Вычислить обратную не получится, т.к. для этого она должна быть квадратной.

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [79]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел 
от 0 до 16 невключительно. 

In [83]:
c = np.arange(16)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу 
B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [84]:
C = c.reshape(4,4)
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [88]:
D = B+C*10
D

array([[  5,  24,  43,  62],
       [ 54, 100, 146, 192],
       [103, 176, 249, 322],
       [152, 252, 352, 452]])

In [89]:
np.linalg.matrix_rank(D)

2

In [90]:
np.linalg.det(D)

5.18953807259442e-26

In [91]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 4.66062690e+13, -1.49229688e+13, -1.09972869e+14,
         7.82895692e+13],
       [ 1.63480451e+14, -3.81454387e+14,  2.72467419e+14,
        -5.44934838e+13],
       [-4.66779710e+14,  8.07677680e+14, -2.15016230e+14,
        -1.25881740e+14],
       [ 2.56692989e+14, -4.11300324e+14,  5.25216801e+13,
         1.02085655e+14]])

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
Убедитесь, что в матрице D_inv остались только нули и единицы. 
С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, 
получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, 
должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, 
для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [97]:
timeit D_inv[D_inv > 0] = 1

3.21 µs ± 240 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [99]:
timeit D_inv[D_inv < 0] = 0

3 µs ± 633 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [100]:
D_inv

array([[1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 1.]])

In [104]:
E = np.where([True,False,False,True],B,C)
E

array([[  5,   1,   2,  32],
       [ 14,   5,   6, 122],
       [ 23,   9,  10, 212],
       [ 32,  13,  14, 302]])